### ISSUE TITLE
Why create and return a task?

### ISSUE THREAD

**Issue by alexmojaki** [gsmecher/awaitless#3]
Why does this transform `hello()` into:

```python
_ttemp = hello()
if inspect.iscoroutine(_ttemp):
    _ttemp = asyncio.create_task(_ttemp)
    await _ttemp
_ttemp
```

instead of

```python
_ttemp = hello()
if inspect.iscoroutine(_ttemp):
    _ttemp = await _ttemp
_ttemp
```

??

**Comment by gsmecher** [comment]
Basically, I have two options here:

1. Add training wheels to asyncio so it's a little more ergonomic (this is the Task() approach), or
2. Try to remove it from top-level code (this is what you're suggesting).

I see the appeal of (2), except it changes the semantics of asynchronous Python code depending on whether you're running in the top level of an ipython cell or not. The Task() option still allows/encourages you to use "await", so you can run the same code with and without awaitless.

**Comment by alexmojaki** [comment]
The suggested code would still allow `await`. Why encourage using it? The README already implies the user shouldn't have to.

> it changes the semantics of asynchronous Python code depending on whether you're running in the top level of an ipython cell or not.

This is already the case when you transform assignments:

```python
In [1]: async def task(i): print(f'doing task {i}')

In [3]: t1 = task(1)

In [4]: t2 = task(2)

In [5]: tasks = [t1, t2]

In [6]: import asyncio

In [8]: await asyncio.gather(*tasks)
doing task 1
doing task 2
Out[8]: [None, None]

In [9]: load_ext awaitless

In [10]: t1 = task(1)
doing task 1

In [11]: t2 = task(2)
doing task 2
```

**Comment by gsmecher** [comment]
Shifting time of execution from the gather() call to the execution of the inserted AST nodes is deliberate - that's the primary way we improve asyncio ergonomics for interactive code. So, yes, that's a semantic change but it's also the whole point.

It's also why we need something future-like instead of a coroutine - we can only await the coroutine once (and either give the user interactive feedback, or allow them to run the next piece of code that depends on it), but a Task or future can be repeatedly awaited.

**Comment by gsmecher** [comment]
Is your alternate suggestion (above) intended for Expr, or Assign, or both?

**Comment by alexmojaki** [comment]
OK, I see how the task helps with assignments. I was thinking that my version would still work with `x = await hello()`, but I can see that it doesn't work with `x = hello(); await x`.

> Is your alternate suggestion (above) intended for Expr, or Assign, or both?

Originally both, now just Expr. Is there a benefit of returning a Task in that case?

**Comment by gsmecher** [comment]
>> Is your alternate suggestion (above) intended for Expr, or Assign, or both?

> Originally both, now just Expr. Is there a benefit of returning a Task in that case?

Basically - the principle of least surprise. I work in a scientific/instrumentation context - so when I reach for non-trivial examples they're also freighted with irrelevant context. Let's imagine some kind of software-defined radio (SDR) hardware tuning into an FM broadcast station:

```
>>> d = remote_device("http://hostname/endpoint")
>>> d.set_frequency(90.1e6, d.UNITS.HZ)
>>> d.get_samples(num_samples=1000)
```

Assume get_samples is an async function that returns (as a coroutine) a dictionary of complex samples as follows:

```
{ 'i': [1, 2, 3, 4, 5, ...], 'q': [1, 2, 3, 4, 5, ...], ... }
```

As written above, the get_samples() call is an Expr and returns one of three things:

1. a coroutine object (what happens without awaitless)
2. a Task that can be awaited (what awaitless does now)
3. the awaited result of the coroutine (what you're suggesting)

Our options are (2) and (3), and (1)'s only listed because we'd better improve on it or we shouldn't have bothered in the first place.

If we follow path (3), then the result is least cluttered and most visible - we get the sample dictionary back without ceremony. However, this invites the user to then proceed as follows:

```
>>> x = d.get_samples(10, channel=1, module=1)
```

They will be surprised when the type of this result (a coroutine in (1), or a Task in (2)) is not what they were shown. Even if we stay within the realm of Expr nodes, an attempt to index the result is also baffling:

```
>>> d.get_samples(10, channel=1, module=1)['i']  # TypeError: 'coroutine' object is not subscriptable
```

...this is exciting, because it applies to (2) and (3) equally. However, (2) gives you a Task (which you also can't subscript), so you're not misled into typing code like this in the first place.

Stepping back - our users are encouraged to prototype code interactively, and then transfer it into Python code that may be executed outside an ipython cell (where our AST transformations no longer take place). I don't want to make that process any more mysterious or fraught than I have to. Hence, (1) or (2), but not (3).

**Comment by gsmecher** [comment]
(hmm, this makes me wonder if we should wrap Call sites too)

**Comment by alexmojaki** [comment]
ok, makes sense
