### ISSUE TITLE
Assignments still transformed too eagerly

### ISSUE THREAD

**Issue by alexmojaki** [gsmecher/awaitless#5]
```python
In [2]: tasks = []

In [4]: async def task(i): print(f'doing task {i}')

In [5]: for i in range(3):
   ...:     t = task(i)
   ...:     tasks.append(t)
   ...:

In [6]: import asyncio

In [7]: await asyncio.gather(*tasks)
   ...:
doing task 0
doing task 1
doing task 2
Out[7]: [None, None, None]

In [8]: load_ext awaitless

In [9]: for i in range(3):
   ...:     t = task(i)
   ...:     tasks.append(t)
   ...:
doing task 0
doing task 1
doing task 2
```

You could say `visit_For = _trigger_inner_context` (and so on for a bunch of other nodes) but I don't think there's a reason to walk the whole AST. I suggest looping over the top level statements in the module and transforming them if they're an Assign/Expr.

**Comment by gsmecher** [comment]
Given the discussion in #3, I'm mulling this one too. We definitely can't insert our AST transformations inside a non-async function:

```
def foo()
   # [...AST modifications would end up here...]
```

...because we'd add an "await", which is illegal syntax in a synchronous context. However, for any other (?) AST node, inserting "await"s is legal.

Set aside for a moment the time-of-execution difference between awaitless ("eager") and non-awaitless ("lazy"). I think there are two ways to justify AST modifications here:

1. Only alter the top level expressions and statements (what you're suggesting), or
2. Alter everything we legally can inside the ipython cell (what's currently done, with the exception of AsyncFunctionDef nodes).

What we currently do (alter FunctionDef and AsyncFunctionDef) is the wrong choice. I am actually leaning towards (2), because otherwise, it's too easy to create visibly different behaviour depending on indentation level.

**Comment by gsmecher** [comment]
After some consideration, I don't actually think there's a practical difference between traversing the children of the ipython cell (`for child in module_node.body`) and traversing the whole AST using generic_visit. I also had to stub out Class nodes to prevent transformations of this type:

```
class Foo:
    x = "something"  # -> AST transformations insert an await in this scope, which is a SyntaxError
```

...but otherwise, everything seems to be already appropriately scoped out by construction. The two approaches are equivalent and it comes down to a matter of code clarity.

Again, I appreciate the drive-by. Your comments have helped me rationalize a thing or three and you've caught a few bugs that would have been harder to diagnose if I'd bumped into them less directly. Thank you!
